### ISSUE TITLE
dbt_utils version dependency?

### ISSUE THREAD

**Issue by antonmcgeezy** [fishtown-analytics/dbt-audit-helper#8]
I'm curious to try out this package but it has a package version specification for dbt_utils locked at <0.2 and of course we are on 0.2.1.  Is this because of a real incompatibility (or inability to test) with the latest version?  I'm hoping it's just an oversight in spec in the packages.yml file ;)  Thanks! Anthony

**Comment by tayloramurphy** [comment]
I'd like to understand this as well. We just upgraded to 0.14 and would like to bring utils up to snuff as well.

@clrcrl ?
